version: "3.3"

services:
  backend:
    build: ./backend
    container_name: django-backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_HOST=${DB_HOST} # ğŸ”¹ é€™è£¡æ‡‰è©²æ˜¯å¤–éƒ¨ MySQL ä¼ºæœå™¨çš„ IP æˆ–ç¶²å€
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./backend:/app
      - static_volume:/app/static
    depends_on: [] # ğŸ”¹ å› ç‚º MySQL åœ¨å¤–éƒ¨ï¼Œæ‰€ä»¥ä¸å†ä¾è³´ `db`
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend/react_frontend
    container_name: react-frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:8080"
    depends_on:
      - backend
    volumes:
      - static_volume:/usr/share/nginx/html/static
    env_file:
      - ./frontend/react_frontend/.env

volumes:
  static_volume:
